source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AdyenCheckout_Example', :exclusive => true do
  pod "AdyenCheckout", :path => "../"
end

target 'AdyenCheckout_Tests', :exclusive => true do
  pod "AdyenCheckout", :path => "../"

#pod 'Quick', '~> 0.3.1'
#  pod 'Nimble'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'
end
